# 服务器配置
server:
    port: 8090
# logback日志配置
logging:
    config: classpath:log/logback-spring.xml
    path: D:/websocket/
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
# Spring配置
spring:
    # 多环境配置
    profiles:
        # 如不指定默认application.yml节点，指定后运行指定配置文件配置
        active:
    # 数据源配置
    datasource:
        username: dlwy
        password: DlwyZmn2017
        url: jdbc:mysql://192.168.1.111:3306/xht_ywp
        #driver-class-name: com.mysql.jdbc.Driver
    # 模板引擎
    freemarker:
        #内容格式
        content-type: text/html
        #缓存配置
        cache: false
        #模板路径
        template-loader-path: classpath:/templates
        #编码格式
        charset: UTF-8
        #是否启用
        enabled: true
        #请求内容属性
        request-context-attribute: request
        expose-request-attributes: true
        expose-session-attributes: true
        #检查模板路径
        check-template-location: true
        #文件后缀
        suffix: .ftl