#服务器设置
server:
    port: 8090
#默认配置
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
        #driver-class-name: com.mysql.jdbc.Driver
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
    typeAliasesPackage: com.boonya.springboot.mybatis.sbmybatis.entity
    mapperLocations: classpath:mapper/*.xml



