# 服务配置
server:
    port: 8090
# 数据源配置
spring:
    profiles:
        active: prod
    datasource:
        username: dlwy
        password: DlwyZmn2017
        url: jdbc:mysql://192.168.1.111:3306/xht_ywp
        driver-class-name: com.mysql.jdbc.Driver
