server:
    port: 8090
logging:
    config: classpath:log/logback-spring.xml
    path: D:/websocket/
    level:
        root: ERROR
        org.springframework.web: INFO
        org.springframework.security: INFO
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
        #driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        cache: false
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
    typeAliasesPackage: com.boonya.springboot.mybatis.sbmybatis.entity
    mapperLocations: classpath:mapper/*.xml